spring:
  application:
    name: clean-architecture-ddd
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/clean-architecture-ddd
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
